# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-08 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190607_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrcidToken',
        ),
        migrations.RemoveField(
            model_name='account',
            name='orcid',
        ),
    ]
