# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0033_frozenauthor_is_corporate'),
        ('submission', '0033_merge_20190326_1556'),
    ]

    operations = [
    ]
